CREATE DATABASE IF NOT EXISTS api;
use api;
CREATE TABLE particle(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, type VARCHAR(250), tid INT, charge DOUBLE, spin INT, mass DOUBLE, price DOUBLE, quantity BIGINT);
CREATE TABLE sales(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, type VARCHAR(250), tid INT, charge DOUBLE, spin INT, mass DOUBLE, price DOUBLE, quantity BIGINT);